#Some comments
ServerRoot:

#Some comments
DocumentRoot:

#Port by default
Listen 80 

#Some comments
ErrorLog: 

#Some comments
LogLevel: 

PHPIniDir "Your path here"

# Deny access for this directory
<Directory />
    AllowOverride none
    Require all denied
</Directory>

# If a directory is requested, Apache will send the file "myFile.html"
<IfModule dir_module>
    DirectoryIndex myFile.html
</IfModule>

# Secure connections with SSL and TLS encryption
Include httpd-ssl.conf

<IfModule ssl_module>
    SSLRandomSeed startup builtin
    SSLRandomSeed connect builtin
</IfModule>

# Hide Apache version
ServerSignature Off
ServerTokens Prod