#Some comments
ServerRoot:

#Some comments
DocumentRoot:

#Port by default
Listen 80 

#Some comments
ErrorLog: 

#Some comments
LogLevel: 

PHPIniDir "Your path here"

# Deny access for this directory
<Directory />
    AllowOverride none
    Require all denied
</Directory>

# If a directory is requested, Apache will send the file "myFile.html"
<IfModule dir_module>
    DirectoryIndex myFile.html
</IfModule>

# Secure connections with SSL and TLS encryption
Include httpd-ssl.conf

<IfModule ssl_module>
    SSLRandomSeed startup builtin
    SSLRandomSeed connect builtin
</IfModule>

<VirtualHost xxx.xxx.x.x:443>
    DocumentRoot /var/www/examplesite
    ServerName example.com www.example.com
    SSLEngine on
    SSLCertificateFile /path/to/examplesite.crt
    SSLCertificateKeyFile /path/to/privatekey.key
    SSLCertificateChainFile /path/to/intermediate.crt
</VirtualHost>

# Hide Apache version
ServerSignature Off
ServerTokens Prod